various fixes, optimizations + added perfdata for ram and disks

diff --git a/check_ctxhypervisor_health b/check_ctxhypervisor_health
--- a/check_ctxhypervisor_health
+++ b/check_ctxhypervisor_health
@@ -4,64 +4,48 @@
  * @package   check_ctxhypervisor_health
  * @copyright check_ctxhypervisor_health contributors
  * @license   GNU Affero General Public License (https://www.gnu.org/licenses/agpl-3.0.de.html)
- * parts of this software (class Xenapi) is @copyright by Andy Goodwin with a custom license.
+ * parts of this software (class Xenapi - see below) is @copyright by Andy Goodwin with a custom license.
  * please check the related code further down.
  */
- 
-$options = getopt("h:u:p:w::c::", array("host:", "user:", "password:", "warning::", "critical::"));
 
-// no options defined? 
-if(count($options) == 0)
-{
-    echo "parameter -h || --host (Hostname from the Hypervisor) is missing \n";
-    echo "parameter -u || --user is missing \n";
-    echo "parameter -p || --password is missing \n";
-}
-if(!isset($options['host']) && !isset($options['h']))
-{
-	echo "parameter -h || --host (Hostname from the Hypervisor) is missing \n";
-	exit(0);
-}
+ // our global $context and the params array
+ $context = array();
+ $params = array();
 
-if(!isset($options['user']) && !isset($options['u']))
-{
-	echo "parameter -u || --user is missing \n";
-	exit(0);
-}
-
-if(!isset($options['password']) && !isset($options['p']))
-{
-	echo "parameter -p || --password is missing \n";
-	exit(0);
-}
-
-$xshost = isset($options['host']) ? $options['host'] : $options['h'];
-$xsuser = isset($options['user']) ? $options['user'] : $options['u'];
-$xspassword = isset($options['password']) ? $options['password'] : $options['p'];
-$warning = isset($options['warning']) ? $options['warning'] : isset($options['w']) ? $options['w'] : 90;
-$critical = isset($options['critical']) ? $options['critical'] : isset($options['c']) ? $options['c']: 95;
-$is_poolmaster = false;
-
-$context = array();
-$xshost = 'https://' . $xshost;
+ // get all params from the command line call
+ $params = getParams();
 
 // get all the important data from the Hypervisor
-$context['system'] = getXenserverDetails($xshost, $xsuser, $xspassword, $warning, $critical);
+$context['system'] = getXenserverDetails($params['xshosturl'], $params['xsuser'], $params['xspassword'], $params['warning'], $params['critical']);
+$context['system']['is_poolmaster'] = $context['is_poolmaster'];
 $exit_code = get_exit_code($context['system']);
 
-renderOutput($context['system'], $exit_code);
+// all data should be there, let's render our data
+renderOutput($context['system'], $params, $exit_code);
 
+/**
+ * this function is the core functionality. it connects to the XenApi class and handles all the data collection.
+ * 
+ * @param string $xshosturl the hypervisors url to name or ip
+ * @param string $login the username we use to connect to the hypervisor api, most likely 'root'
+ * @param string $password the password from our user
+ * @param int $warning some default threshold for warning states
+ * @param int $critical threshold for critical states
+ * 
+ * @return array $details a large associative array with all the collected data 
+ * 
+ */
 
-function getXenserverDetails($xshost, $login, $password, $warning = 90, $critical = 95)
+function getXenserverDetails($xshosturl, $login, $password, $warning = 90, $critical = 95)
 {
     $details = array();
 
-
-		$xenserver = new XenApi($xshost, $login = 'root', $password);
+		$xenserver = new XenApi($xshosturl, $login = 'root', $password);
           
         //get all hosts from the conneted pool. Unfortunately we can only connect to the poolmaster..
         $hosts = $xenserver->host__get_all();
 
+        // lets also check all guests or we won't get the not running guests..
         $poolguests = $xenserver->VM__get_all();
 
 		foreach ($hosts as $host)
@@ -69,8 +53,7 @@ function getXenserverDetails($xshost, $login, $password, $warning = 90, $critica
 		    $record = $xenserver->host__get_record($host);
 
             //Hostname or IP identical?
-            
-            if (('https://' . $record['name_label']) == $xshost || ('https://' . $record['address']) == $xshost)
+            if (('https://' . $record['name_label']) == $xshosturl || ('https://' . $record['address']) == $xshosturl)
             {
                 $details['host']['name'] = $record['hostname'];
                 $details['host']['vendor'] = $record['bios_strings']['system-manufacturer'];
@@ -79,7 +62,7 @@ function getXenserverDetails($xshost, $login, $password, $warning = 90, $critica
                 $details['host']['version'] = $record['software_version']['product_brand'] . ' ' . $record['software_version']['product_version'];
                 $details['host']['cpu'] = $record['cpu_info']['modelname'] . "(" . $record['cpu_info']['socket_count'] . " Sockets - ". $record['cpu_info']['cpu_count'].  " CPU)";
                                
-                //PBDs & SR details
+                // get the PBDs & SR details
                 foreach ($record['PBDs'] as $pbd)
 			    {
                     $pbd_list = $xenserver->PBD__get_record($pbd);
@@ -126,7 +109,7 @@ function getXenserverDetails($xshost, $login, $password, $warning = 90, $critica
                     'exit_code' => $usage > $critical ? 2 : ($usage > $warning ? 1 : 0)
                 );
 
-                //VMS
+                // get the resident VMs from our hypervisor
                 foreach ($record['resident_VMs'] as $guests)
 			    {
 				    $rec = $xenserver->VM__get_record($guests);
@@ -141,6 +124,7 @@ function getXenserverDetails($xshost, $login, $password, $warning = 90, $critica
             }
         }
         
+        // get all guests from the pool
         foreach ($poolguests as $pool_guests)
         {
             $rec = $xenserver->VM__get_record($pool_guests);
@@ -197,6 +181,14 @@ function array_value_recursive($key, array $arr)
     return count($val) > 1 ? $val : array_pop($val);
 }
 
+/**
+ * format the text input with Thruk color codes.
+ * @param string $txt the text we wan't to colorize
+ * @param int $exit_code the exit code, so we know about ok, warning and critical
+ * 
+ * @return string
+ */
+
 function formatStatus ($txt, $exit_code = 4)
 {
 	$green = '#66bb6a';
@@ -225,24 +217,26 @@ function formatStatus ($txt, $exit_code = 4)
  * @param array $data
  * @param int $exit_code
  */
-function renderOutput($data, $exit_code) {
+function renderOutput($data, $params, $exit_code) {
 
-    global $is_poolmaster;
-
+    // everything is fine
    if ($exit_code == 0){
-        echo "OK: Hypevisor " . $data['host']['name'] . "(" . $data['host']['vendor'] . " - ". $data['host']['model'] . " - SN:" . $data['host']['sn'] . ") is healthy.\n";
+        echo "OK: Hypervisor " . $data['host']['name'] . " (" . $data['host']['vendor'] . " - ". $data['host']['model'] . " - SN:" . $data['host']['sn'] . ") is healthy.\n";
     }
 
+    // houston, we have a problem..
     elseif ($exit_code == 1){
-        echo "WARNING: Hypevisor " . $data['host']['name'] . "(" . $data['host']['vendor'] . " - ". $data['host']['model'] . " - SN:" . $data['host']['sn'] . ") reported problems. please check details...\n";
+        echo "WARNING: Hypervisor " . $data['host']['name'] . " (" . $data['host']['vendor'] . " - ". $data['host']['model'] . " - SN:" . $data['host']['sn'] . ") reported problems. please check details...\n";
     }
-     
+    
+    // oooops, this should better not happen for this host..
     elseif ($exit_code == 2){
-        echo "CRITICAL: Hypevisor " . $data['host']['name'] . "(" . $data['host']['vendor'] . " - ". $data['host']['model'] . " - SN:" . $data['host']['sn'] . ") reported problems. please check details...\n";
+        echo "CRITICAL: Hypervisor " . $data['host']['name'] . " (" . $data['host']['vendor'] . " - ". $data['host']['model'] . " - SN:" . $data['host']['sn'] . ") reported problems. please check details...\n";
     }
 
+    // some basic system information like vendor, model & serial number..
     echo "Hypervisor Version: " . $data['host']['version'] . "\n";
-    echo "Poolmaster: " . ($is_poolmaster == true ? "Master" : "Slave") . "\n";
+    echo "Pool role: " . ($data['is_poolmaster'] == true ? "Master" : "Slave") . "\n";
     echo "Vendor: " . $data['host']['vendor'] . "\n";
     echo "Model: " . $data['host']['model'] . "\n";
     echo "SN: " . $data['host']['sn'] . "\n";
@@ -257,20 +251,83 @@ function renderOutput($data, $exit_code) {
         echo $storage['label'] . " - Usage: " . formatStatus($storage['usage'] . "%", $storage['exit_code']) . " (Free: " . $storage['free'] . " GB - Used: " . $storage['used'] . " GB - Total: " .$storage['total'] . " GB)\n";
     }
 
-    echo "\n<b>Guests running on this host:</b>\n";
+    // VMs
     if (!empty($data['guests'] ))
     {
+        echo "\n<b>Guests on this host:</b>\n";
+
         foreach ($data['guests'] as $guest)
         {
             if ($guest['powerstate'] == 'Running')
                 echo '<span style="color: #66bb6a;">&#9679;</span> ' .  $guest['name'] . "\n";
         
-            if ($guest['powerstate'] != 'Running' &&  $is_poolmaster == true)
+            // VMs not running only for the poolmaster..
+            if ($guest['powerstate'] != 'Running' &&  $data['is_poolmaster'] == true)
                 echo '<span style="color: #f0666c;">&#9679;</span> ' .  $guest['name'] . "\n";
         }
     }
-    
+
+    echo '| \'memory usage\'=' . $data['memory']['usage'] . ';' . $params['warning'] . ';' . $params['critical'] . ';0;100';
+
+    foreach ($data['storage'] as $storage)
+    {
+        $w = round($storage['total'] * $params['warning'] / 100, 2);
+        $c = round($storage['total'] * $params['critical'] / 100, 2);
+
+        echo ' \'' . $storage['label'] . '\'=' . $storage['used'] . ';'. $w . ';' . $c .';0;' . $storage['total']. "\n";
+    }
+
+
+    // Performance data
+    //    | 'CPU1'=16;0;0;; 'CPU2'=7;0;0;; 'CPU3'=6;0;0;;
+
 }
+
+/**
+ * get all the important parameters from the command line and place them into an array
+ * @return array $params
+ */
+function getParams() {
+
+    $options = getopt("h:u:p:w::c::", array("host:", "user:", "password:", "warning::", "critical::"));
+
+    // no options defined? 
+    if(count($options) == 0)
+    {
+        echo "parameter -h || --host (Hostname from the Hypervisor) is missing \n";
+        echo "parameter -u || --user is missing \n";
+        echo "parameter -p || --password is missing \n";
+    }
+    if(!isset($options['host']) && !isset($options['h']))
+    {   
+	    echo "parameter -h || --host (Hostname from the Hypervisor) is missing \n";
+	    exit(0);
+    }
+
+    if(!isset($options['user']) && !isset($options['u']))
+    {
+	    echo "parameter -u || --user is missing \n";
+	    exit(0);
+    }
+
+    if(!isset($options['password']) && !isset($options['p']))
+    {
+	    echo "parameter -p || --password is missing \n";
+	    exit(0);
+    }
+
+    $params['xshost'] = isset($options['host']) ? $options['host'] : $options['h'];
+    $params['xsuser'] = isset($options['user']) ? $options['user'] : $options['u'];
+    $params['xspassword'] = isset($options['password']) ? $options['password'] : $options['p'];
+    $params['warning'] = isset($options['warning']) ? $options['warning'] : isset($options['w']) ? $options['w'] : 90;
+    $params['critical'] = isset($options['critical']) ? $options['critical'] : isset($options['c']) ? $options['c']: 95;
+    $params['is_poolmaster'] = false;
+    $params['xshosturl'] = 'https://' . $params['xshost'];
+    
+    return $params;
+}
+
+
 
 
 /*
@@ -312,7 +369,7 @@ class XenApi {
 
     function __construct ($url, $user, $password) {
 
-        global $is_poolmaster;
+        global $context;
 
         $r = $this->xenrpc_request($url, $this->xenrpc_method('session.login_with_password', array($user, $password, '1.3')));
 
@@ -322,18 +379,19 @@ class XenApi {
             $this->_url = $url;
             $this->_user = $user;
             $this->_password = $password;
-            $is_poolmaster = true;
+            $context['is_poolmaster'] = true;
         } else 
 		{
 			if ($r['ErrorDescription'][0] == 'HOST_IS_SLAVE')
 			{
-				$r2 = $this->xenrpc_request($r['ErrorDescription'][1], $this->xenrpc_method('session.login_with_password', array($user, $password, '1.3')));
-				if (is_array($r2) && $r2['Status'] == 'Success') 
+				$ra = $this->xenrpc_request($r['ErrorDescription'][1], $this->xenrpc_method('session.login_with_password', array($user, $password, '1.3')));
+				if (is_array($ra) && $ra['Status'] == 'Success') 
 				{
-					$this->_session_id = $r2['Value'];
+					$this->_session_id = $ra['Value'];
 					$this->_url = $r['ErrorDescription'][1];
 					$this->_user = $user;
-					$this->_password = $password;
+                    $this->_password = $password;
+                    $context['is_poolmaster'] = false;
 				}
 			}
 			else
